name: prometheus
version: master
summary: The Prometheus monitoring system and time series database
description: |
  Prometheus is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts if some condition is observed to be true.
confinement: strict
apps:
  prometheus:
    command: 'bin/prometheus.wrapper'
    plugs: [network-bind, network]
    daemon: simple
parts:
  prometheus:
    plugin: go
    source: https://github.com/prometheus/prometheus.git
    go-importpath: github.com/prometheus/prometheus
  example-config:
    plugin: dump
    source: https://github.com/prometheus/prometheus.git
    source-type: git
    organize:
      documentation/examples/prometheus.yml: etc/prometheus/prometheus.yml.example
    snap:
      - etc/prometheus/prometheus.yml.example
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      snap_config_wrapper: bin/prometheus.wrapper
      daemon_arguments: etc/prometheus/daemon_arguments.example
    snap:
      - bin/prometheus.wrapper
      - etc/prometheus/daemon_arguments.example
