name: prometheus
version: 2.1.0
grade: stable
summary: The Prometheus monitoring system and time series database
description: |
  Prometheus is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts if some condition is observed to be true.
confinement: strict
apps:
  prometheus:
    command: 'bin/prometheus.wrapper'
    plugs: [network-bind, network, content]
    daemon: simple
    stop-timeout: 900s
  promtool:
    command: 'bin/promtool'
plugs:
  content:
    content: promreg
    target: $SNAP_DATA/promreg
parts:
  prometheus:
    plugin: go
    source: https://github.com/prometheus/prometheus.git
    source-tag: v2.1.0
    go-importpath: github.com/prometheus/prometheus
    build-packages: [golang-1.8]
    build: |
        # Make sure we use go 1.8
        export "PATH=/usr/lib/go-1.8/bin/:$PATH"
        export "GOPATH=$PWD/../go" "PATH=$PATH:$PWD/../go/bin"
        cd ../go/src/github.com/prometheus/prometheus/
        make promu
        make build
    install: |
        mkdir $SNAPCRAFT_PART_INSTALL/bin
        cp -p $SNAPCRAFT_PART_INSTALL/../src/promtool $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/prometheus $SNAPCRAFT_PART_INSTALL/bin/
  example-config:
    plugin: dump
    source: https://github.com/prometheus/prometheus.git
    source-tag: v2.1.0
    source-type: git
    organize:
      documentation/examples/prometheus.yml: etc/prometheus/prometheus.yml.example
    stage:
      - etc/prometheus/prometheus.yml.example
    prime:
      - etc/prometheus/prometheus.yml.example
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      snap_config_wrapper: bin/prometheus.wrapper
      daemon_arguments: etc/prometheus/daemon_arguments.example
    stage:
      - bin/prometheus.wrapper
      - etc/prometheus/daemon_arguments.example
    prime:
      - bin/prometheus.wrapper
      - etc/prometheus/daemon_arguments.example
