name: prometheus
version: 2.20.1
base: core18
grade: stable
summary: The Prometheus monitoring system and time series database
description: |
  Prometheus is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts if some condition is observed to be true.
confinement: strict

apps:
  prometheus:
    command: 'bin/prometheus.wrapper'
    plugs: [network-bind, network, content]
    daemon: simple
    stop-timeout: 900s
  promtool:
    plugs: [home]
    command: 'bin/promtool'
plugs:
  content:
    interface: content
    content: promreg
    target: $SNAP_DATA/promreg

parts:
  prometheus:
    plugin: go
    go-channel: 1.14/stable
    source: https://github.com/prometheus/prometheus.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    go-importpath: github.com/prometheus/prometheus
    build-packages: [npm,make]
    override-build: |
        npm install yarn -g
        make build
        mkdir -p $SNAPCRAFT_PART_INSTALL/bin
        mkdir -p $SNAPCRAFT_PART_INSTALL/etc/prometheus
        cp -p $SNAPCRAFT_PART_BUILD/promtool $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_BUILD/prometheus $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_SRC/documentation/examples/prometheus.yml $SNAPCRAFT_PART_INSTALL/etc/prometheus/prometheus.yml.example
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      snap_config_wrapper: bin/prometheus.wrapper
      daemon_arguments: etc/prometheus/daemon_arguments.example
    stage:
      - bin/prometheus.wrapper
      - etc/prometheus/daemon_arguments.example
    prime:
      - bin/prometheus.wrapper
      - etc/prometheus/daemon_arguments.example
