name: prometheus
adopt-info: prometheus
grade: stable
summary: The Prometheus monitoring system and time series database
description: |
  Prometheus is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts if some condition is observed to be true.
confinement: strict

apps:
  prometheus:
    command: 'bin/prometheus.wrapper'
    plugs: [network-bind, network, content]
    daemon: simple
    stop-timeout: 900s
  promtool:
    plugs: [home]
    command: 'bin/promtool'
plugs:
  content:
    content: promreg
    target: $SNAP_DATA/promreg

parts:
  go:
    source-tag: go1.12
  prometheus:
    after: [go]
    plugin: go
    source: https://github.com/prometheus/prometheus.git
    go-importpath: github.com/prometheus/prometheus
    build: |
        export "GOPATH=$PWD/../go"
        cd ../go/src/github.com/prometheus/prometheus/
        version="$(git tag -l | grep -v '\-rc' | sort -V | tail -n 1)"
        snap_version=$(echo $version | sed -e s/^v//)
        snapcraftctl set-version "$snap_version"
        git checkout tags/$version
        make build
    install: |
        mkdir $SNAPCRAFT_PART_INSTALL/bin
        mkdir -p $SNAPCRAFT_PART_INSTALL/etc/prometheus
        cp -p $SNAPCRAFT_PART_INSTALL/../src/promtool $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/prometheus $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/documentation/examples/prometheus.yml $SNAPCRAFT_PART_INSTALL/etc/prometheus/prometheus.yml.example
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      snap_config_wrapper: bin/prometheus.wrapper
      daemon_arguments: etc/prometheus/daemon_arguments.example
    stage:
      - bin/prometheus.wrapper
      - etc/prometheus/daemon_arguments.example
    prime:
      - bin/prometheus.wrapper
      - etc/prometheus/daemon_arguments.example
