version: '2'

services:
    prometheus:
        image: ubuntu/prometheus:edge
        network_mode: "host"
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/alerts.yml:/etc/prometheus/alerts.yml
